### PR TITLE
Added pathway_order and next_step to a list

### PR DESCRIPTION
**Pull request by tmushayahama**
Added pathway_order and next_step to list_types and initialized with empty list. Some of the Pathways have multiple PathwayOrders and PathwayStep have multiple next Steps. 

image

### CODE REVIEW

**Comment by bgyori** [comment]
Thanks @tmushayahama I agree these are all good changes! Would you mind pointing me to the BioPAX file from which you got the screenshot so I can test it out?

**Review by bgyori — APPROVED** [review]

**Comment by tmushayahama** [comment]
Thanks @bgyori
The files are located here on the Reactome site:  When on the site click biopax -> level3 to download as shown below

- https://reactome.org/content/detail/R-HSA-204174
- https://reactome.org/content/detail/R-HSA-70171

image

**Comment by tmushayahama** [comment]
@bgyori is this now ready for release on pypi?

**Comment by bgyori** [comment]
Sure, I just released v0.1.4.

**Pull request merged**
