### PR TITLE
Add additional BioPAX remote resources

### PR DESCRIPTION
**Pull request by cthoyt**
This PR adds getters for:

- [Reactome](https://reactome.org/)
- [MetaCyc](https://metacyc.org/)/[EcoCyc](https://ecocyc.org/)/[HumanCyc](https://humancyc.org/)/[BioCyc](https://biocyc.org/)
- [NetPath](http://netpath.org)

This is also useful for #11 since I can get a larger variety of sources that hopefully cover more of the BioPAX specification

## Next time

- [PathBank](https://pathbank.org/)/[SMPDB](https://smpdb.ca/)

there are weird SSL issues with these, so I'll save them here for later

```python
def model_from_smpdb(identifier: str) -> BioPaxModel:
    """Return a BioPAX model from a `SMPDB <ttps://smpdb.ca>`_ entry.

    Parameters
    ----------
    identifier :
        The PathBank identifier for a pathway (e.g., ``SMP0000060`` for `Pyruvate
        Metabolism <https://smpdb.ca/view/SMP0000060>`_

    Returns
    -------
    :
        A BioPAX model obtained from the SMPDB resource.
    """
    url = f"http://smpdb.ca/view/{identifier}/download?type=owl_markup"
    return model_from_owl_url(url, verify=False)


def model_from_pathbank(identifier: str) -> BioPaxModel:
    """Return a BioPAX model from a `PathBank <https://pathbank.org>`_ entry.

    Parameters
    ----------
    identifier :
        The PathBank identifier for a pathway (e.g., ``SMP0000464`` for `Vitamin K
        Metabolism <https://pathbank.org/view/SMP0000464>`_

    Returns
    -------
    :
        A BioPAX model obtained from the PathBank resource.
    """
    url = f"http://pathbank.org/view/{identifier}/download?type=owl_markup"
    return model_from_owl_url(url, verify=False)

def test_get_smpdb():
    m = pybiopax.model_from_smpdb("SMP0000060")
    assert isinstance(m, BioPaxModel)
    assert m.xml_base == "http://smpdb.ca/pathways/#"
    assert 0 < len(m.objects)


def test_get_pathbank():
    m = pybiopax.model_from_pathbank("SMP0000464")
    assert isinstance(m, BioPaxModel)
    assert m.xml_base == "http://smpdb.ca/pathways/#"
    assert 0 < len(m.objects)
```

### CODE REVIEW

**Comment by bgyori** [comment]
I fixed a few things, haven't yet figured out why some tests fail.

**Comment by cthoyt** [comment]
I'm also vexed by these SSL errors... I don't think it's related to the code. The unit tests seem to work on my system without getting the same error. It seems to be consistent across several python versions, too

**Comment by cthoyt** [comment]
Things I've tried in various combinations combinations to fix the SSL issue that have all failed so far:

1. Make sure `pip install --upgrade certifici`
2. Add `verify=False` on all calls to `requests.get`
4. Add header with `User-agent` to all requests
3. Switch all URLs from having https to http
4. Switch from `requests` to the builtin library `urllib`

**Comment by cthoyt** [comment]
@bgyori I got it to work for most. Let's skip pathbank/smpdb for now and maybe come back later.

**Pull request merged**
